name: hfsconnectapp
description: HFS Connect app
publish_to: none
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/LogoNoBg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
